### PR TITLE
Project 2: send and receive data from API

### PR DESCRIPTION
**Pull request by er-contreras**
- Read the Leaderboard API documentation to learn how to use this API
- Create a new game with the name of your choice by using the API.
- Implement the "Refresh" button (receiving data from the API and parsing the JSON).
- Implement the form "Submit" button (sending data to the API).

### CODE REVIEW

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by er-contreras** [comment]
Hello, @arslanbisharat 

I see that you approved my project but I see in my view progress "required changes". can you help me with that?

should I request a review again?

**Comment by arslanbisharat** [comment]
> Hello, @arslanbisharat 
> 
> I see that you approved my project but I see in my view progress "required changes". can you help me with that?
> 
> should I request a review again?

Where are required changes ?

**Comment by arslanbisharat** [comment]
> Hello, @arslanbisharat
> 
> I see that you approved my project but I see in my view progress "required changes". can you help me with that?
> 
> should I request a review again?

I am sorry for the mistake but I think I marked it approved. 

No, you don't need to. I will request Dev Team to update the status.

**Comment by er-contreras** [comment]
> > Hello, @arslanbisharat
> > I see that you approved my project but I see in my view progress "required changes". can you help me with that?
> > should I request a review again?
> 
> I am sorry for the mistake but I think I marked it approved.
> 
> No, you don't need to. I will request Dev Team to update the status.

Thanks,  have a nice day!

**Pull request merged**
